version: '3.7'

services:
 azure-sql-edge:
    image: mcr.microsoft.com/azure-sql-edge:latest
    container_name: sql-server-samples-persistence
    cap_add:
      - SYS_PTRACE
    ports:
      - "1433:1433"
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "abcD1234!"
    volumes:
      - ./var/opt/mssql:/var/opt/mssql
      - ./var/opt/mssql/backup:/var/opt/mssql/backup/
